Make InventoryManipulation available to all rake tasks
Previously this was guarded by the existence of a inventory.yaml file,
which could lead to errors when trying to chain operations:

```
~/git/puppetlabs-motd$ rm inventory.yaml
~/git/puppetlabs-motd$ bundle exec rake litmus:provision[docker,litmusimage/debian:9] litmus:install_agent litmus:install_module
Provisioning litmusimage/debian:9 using docker provisioner.[✔]
localhost:2223, litmusimage/debian:9
rake aborted!
NameError: undefined local variable or method `inventory_hash_from_inventory_file' for main:Object
/home/david/gems/ruby/2.5.0/gems/puppet_litmus-0.15.0/lib/puppet_litmus/rake_tasks.rb:104:in `block (2 levels) in <top (required)>'
/home/david/gems/ruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => litmus:install_agent
(See full trace by running task with --trace)
~/git/puppetlabs-motd$
```